This is a testharness.js-based test.
[FAIL] Test presentation.receiver.connectionList resolves with incoming connection.
  promise_test: Unhandled rejection with value: object "ReferenceError: internals is not defined"
Harness: the test ran to completion.
