This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = Traceback (most recent call last):\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 511, in run_func\n    self.result = True, self.func(self.protocol, self.url, self.timeout)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 612, in do_testharness\n    done, rv = handler(result)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/base.py", line 738, in __call__\n    return callback(url, payload)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/base.py", line 753, in process_action\n    with ActionContext(self.logger, self.protocol, payload.get("context")):\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/base.py", line 795, in __enter__\n    self.protocol.testdriver.switch_to_window(self.context, self.initial_window)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/protocol.py", line 501, in switch_to_window\n    raise Exception("Window with id %s not found" % wptrunner_id)\nException: Window with id False not found\n
Harness: the test ran to completion.
