This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = Traceback (most recent call last):\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 511, in run_func\n    self.result = True, self.func(self.protocol, self.url, self.timeout)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 621, in do_testharness\n    protocol.testharness.close_old_windows()\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorchrome.py", line 93, in close_old_windows\n    for handle in self.webdriver.handles:\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/client.py", line 22, in inner\n    return func(self, *args, **kwargs)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/client.py", line 671, in handles\n    return self.send_session_command("GET", "window/handles")\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/client.py", line 603, in send_session_command\n    return self.send_command(method, url, body, timeout)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/client.py", line 555, in send_command\n    response = self.transport.send(\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/transport.py", line 234, in send\n    response = self._request(method, uri, payload, headers, timeout=None)\n  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/transport.py", line 259, in _request\n    response = self.connection.getresponse()\n  File "/b/s/w/ir/.task_template_vpython_cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/http/client.py", line 1344, in getresponse\n    response.begin()\n  File "/b/s/w/ir/.task_template_vpython_cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n  File "/b/s/w/ir/.task_template_vpython_cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/http/client.py", line 276, in _read_status\n    raise RemoteDisconnected("Remote end closed connection without"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n
Harness: the test ran to completion.
