This is a testharness.js-based test.
[FAIL] sysex permission grants are properly handled
  promise_test: Unhandled rejection with value: object "ReferenceError: internals is not defined"
Harness: the test ran to completion.
